image: ruby:2.5
cache:
  paths:
  - .bundle
variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle --path .bundle/gems

test:
  stage: test
  script:
  - bundle exec jekyll build -d test --config _config.yml,_config_development.yml
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public --config _config.yml -q
  artifacts:
    paths:
    - public
  only:
  - master
