---
#permalink: /:categories/:title/
author: Takayuki Konishi
layout: single
classes: wide
categories: trial
tags: openstack
ref: openstack
lang: ja
locale: ja
toc: true
toc_label: 目次
---
= OpenStack all-in-oneを試す

== はじめに
中古のワークステーションをヤフオクで手に入れて、OpenShiftをインストールしたいもののインストーラーを使うにはOpenStackかRed Hat Virtualization、VMware vSphereのいずれかが必要なのでインストールに挑戦してみます。

[.notice--warning]
NOTE: このドキュメントは実験的な内容です。OpenStackは初めて触るので、適切な方法でない可能性が高く、正式なドキュメントを参照してください。

== 参考にしたページ
* link:https://qiita.com/konono/items/76747f39a44992f446c6[OpenShiftを爆速でインストールしたいあなたへ]
** OCP4 1クラスターをベアメタルにインストールする手順です。しかし今回の目的には合いません。
* link:https://github.com/redhat-openstack/infrared/tree/stable[Infrared]
** OpenStackを簡単にインストールするツールです。今回使えるかもしれません。
* link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/quick_start_guide/index[Red Hat OpenStack Platform 16 Quick Start Guide]
** オフィシャルドキュメントなので一番正しいドキュメントですが、知識がないので読み解けるか自信はありません。

== OpenShift側の要件
* link:https://access.redhat.com/articles/4679401[OpenShift Container Platform on Red Hat OpenStack Platform Support Matrix]
** OCP 4.5はOSP 13と16.1へのインストールをサポートします。

== Infrared調査
InfraredによるOSP 13のインストール手順はいただいているので、Infraredを調べてみます。

=== link:https://infrared.readthedocs.io/en/stable/setup.html[Supported distros]
____
Currently supported distros are:

    Fedora 25, 26, 27
    RHEL 7.3, 7.4, 7.5
____
うーん、Infraredのドキュメントは、最近は更新されていないですね…。とはいえターゲットのワークステーションは2014年製造と古いので、RHEL 7.xは確実に動くでしょうし、確実性を取ったほうがいいかもしれません。

== All-in-one Red Hat OpenStack Platform installationの調査