---
#permalink: /:categories/:title/
author: Takayuki Konishi
layout: single
classes: wide
categories: trial
tags: openstack
ref: openstack
lang: ja
locale: ja
toc: true
toc_label: 目次
---
= OpenStack all-in-oneを試す

== はじめに
中古のワークステーションをヤフオクで手に入れたので、link:https://www.openshift.com/products/container-platform[Red Hat OpenShift Container Platform](OCP) 4.5をインストールします。しかしOCP 4.5のインストーラーが対応しているオンプレミス環境は、link:https://www.redhat.com/ja/technologies/linux-platforms/openstack-platform[Red Hat OpenStack Platform](OSP)かRed Hat Virtualization、VMware vSphereのいずれかです。ここではOSPのインストールに挑戦します。

[.notice--warning]
NOTE: このドキュメントは実験的な内容です。OSPは初めて触るので、適切な方法でない可能性があります。公式のドキュメントを参照してください。

== 参考にしたページ
* link:https://qiita.com/konono/items/76747f39a44992f446c6[OpenShiftを爆速でインストールしたいあなたへ]
** OCP4 1クラスターをベアメタルにインストールする手順です。しかし今回の目的には合いません。
* link:https://github.com/redhat-openstack/infrared/tree/stable[Infrared]
** OpenStackを簡単にインストールするツールです。今回使えるかもしれません。
* link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/quick_start_guide/index[Red Hat OpenStack Platform 16.1 Quick Start Guide]
** オフィシャルドキュメントなので一番正しいドキュメントですが、知識がないので読み解けるか自信はありません。
* link:https://access.redhat.com/articles/1127153[Evaluating OpenStack: Single-Node Deployment]

== OpenShift側の要件
* link:https://access.redhat.com/articles/4679401[OpenShift Container Platform on Red Hat OpenStack Platform Support Matrix]
** OCP 4.5はOSP 13と16.1へのインストールをサポートします。

== OpenStackのサポート状況
link:https://access.redhat.com/support/policy/updates/openstack/platform[Red Hat OpenStack Platform Life Cycle]

RHOSP 13はすでにメンテナンスサポートフェーズで、2021年6月末で延長サポートフェーズに入ります。もう少し長いサポートが欲しいので、できれば16を使いたいです。

== Infrared調査
InfraredによるOSP 13のインストール手順はいただいているので、Infraredを調べてみます。

=== link:https://infrared.readthedocs.io/en/stable/setup.html[Supported distros]
____
Currently supported distros are:

    Fedora 25, 26, 27
    RHEL 7.3, 7.4, 7.5
____
Infraredのドキュメントは、最近は更新されていないようです。とはいえターゲットのワークステーションは2014年製造と古いので、RHEL 7.xは確実に動くでしょうし、確実性を取ったほうがいいかもしれません。
RHEL 8のリポジトリを見てみましたが、OpenStack 13はありませんでした。今後追加されるかもしれませんが、RHEL 7を使うか、OSP 16.1を使うのがよさそうです。

この調査をしているうちに OSP 16.1がリリースされたので、ひとまずこのバージョンでの構築に挑戦します。

== All-in-one OSP
本来OSPは複数のサーバーにコンポーネントを分散してデプロイするものですが、検証用に1台のサーバーにインストールする手順が公開されています。

=== 要件

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1-beta/html/quick_start_guide/all-in-one-openstack-installation[Example network configuration]
____
Example network configuration

    Interface eth0 assigned to the default network 192.168.122.0/24
    Interface eth1 assigned to the management network 192.168.25.0/24 
____

ネットワークインターフェースが2個必要と書いてあります。当然ながらセグメントも分ける必要があります。とはいえAll-in-oneならマネジメントネットワークにつながる他のサーバーは無いので、物理的にはインターフェース1個でもいいのかもしれません。

== ハードウェア

サーバー: Dell Precision T7610
CPU: Xeon E5-2670v2 10コア x 2 
GPU: NVIDIA Quadro K5000
ストレージ: SSD 256GB x 2

これらは落札したサーバーに付属していました。メモリも32GB付属していましたが、eBayで落札した以下のメモリに換装しました。またSSDも追加しました。

メモリ: 512GB (16x32GB) DDR3 PC3L-10600L 4Rx4 ECC Server Memory 
ストレージ: SSD 1TB x 2

== インストール前作業

OSPインストール前に以下のような作業を行いました。

=== ハードウェアセットアップ

. T7610動作確認
. メモリ換装
. SSD増設

=== SW

. BIOS更新
. RHEL 8.1インストール、登録
. ホスト名の設定 - osp.home.seannos.io

== ストレージの設定

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/storage_guide/index[Storage Guide Red Hat OpenStack Platform 16.1 | Red Hat Customer Portal]

=== cinder-volumesの設定

tripleo-heat-installer-templates/deployment/cinder/cinder-common-container-puppet.yaml に、

`/var/lib/cinder/cinder-volumes`が無ければループバックデバイスを作成する処理があるように見えるので、`/var/lib/cinder/cinder-volumes` にSSDを割り当てます。
ループバックデバイスは、サイズがデフォルトで10GBしかないので役に立ちません。

____
                shell: |-       
                  exit_code=0   
                  existing_device=$(losetup -j /var/lib/cinder/cinder-volumes -l -O NAME | tail -n-1)
                  if [[ -z "${existing_device}" ]]; then
                      losetup -f /var/lib/cinder/cinder-volumes --show
                      exit_code=2     
                  else          
                      echo ${existing_device%$'\n'*}
                  fi            
                  exit ${exit_code}   
____

この方法はダメでした。

OpenStackのドキュメントには、 link:https://docs.openstack.org/mitaka/install-guide-rdo/cinder-storage-install.html[Cinderをインストールする手順] の記載があります。該当するストレージをLVMボリュームスキャンから除外するなどの案内がありますが、そもそも手順がかなり違うのでトラブルがない限り、無視しておきます。

結論: vgectend、lvextend で cinder-volumes VGに追加する。
TODO: 後でcinderの容量を確認

=== swiftの設定

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/storage_guide/ch-manage-containers#con_install-and-configure-storage-nodes-for-rhel_osp-storage-guide[ドキュメント] によれば、ストレージをXFSでフォーマットして、 /srv/node/<デバイス名> でマウントするとSwiftのストレージとして認識されるようです。

== OSPインストール

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/quick_start_guide/index[Quick Start Guide]に記載の手順は、意外なほどスムーズに進みました。

standalone_parameters.yaml は、けっこう見直しが必要。
TODO: 要調査: 一通り全部
CloudDomainに ospがついたものをホスト名にしないといけないようだ。 CloudDomainがexample.comなら、osp.example.comをホスト名にしないといけない
NeutronDNSDomain にマシン名でVMに紐づけられるようだ。NeutronDNSDomain が example.comで VMがcentos ならcentos.example.com が割り当てられる。

link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/overcloud_parameters/core-overcloud-parameters[Core Overcloud Parameters]
定義はこちらにある

CloudDomain: osp.seannos.io
CloudName: overcloud.osp.seannos.io
Debug: true
DeploymentUser: $USER
DnsServer:
  - 192.168.18.1
NeutronPublicInterface: enp7s0
NeutronDnsDomain: local.osp.seannos.io
ControlPlaneStaticRoutes: []


StandaloneEnableRoutedNetworks 定義は見当たらない。UndercloudEnableRoutedNetworks という設定はあるが、関係があるだろうか。

COntrolPlaneStaticRoutes - all-in-oneだと関係無さそう

imageの登録がSELinuxによって阻害されてたようで、再起動したら解決したように見えた。

EdgeRouterXから 192.168.19.0/24にアクセスできないようだ。NICの設定が必要か。
Route 53からサブドメインの委任をするか。

== 設定

network

    external network 名称は datacentre
    Directorガイドに一通り書いてある。

flavor
image


== References

link:https://access.redhat.com/solutions/2210421[How can I revert to a clean undercloud in Red Hat Enterprise Linux Openstack Platform - Red Hat Customer Portal]

link:https://www.slideshare.net/kajinamit/tripleo-deep-dive-11[TripleO Deep Dive 1.1]

link:https://rheb.hatenablog.com/entry/openshift-on-openstack-director-1[OpenShift on OpenStackの一例]